name: C++ CI

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      CACHED_PATHS: |
        bcheck
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install llvm
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 20 all && sudo apt-get remove clang-18

    - name: set gcc-14 default
       # default is 13.2, unfortunately. This makes 14.x work
      run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 14 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14
    - name: set clang-20 default
      run: sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 20 && sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 20
    - name: gcc version check
      run: gcc --version
    - name: clang version check
      run: clang --version
    - name: install packages
      run: sudo apt-get install -y cmake
    - name: build gcc
      run: ./scripts/build.sh -d build_gcc -c gcc
    - name: test gcc
      run: cd build_gcc && ctest
    - name: build clang
      run: ./scripts/build.sh -d build_llvm -c clang
    - name: test clang
      run: cd build_llvm && ctest
