name: C++ CI

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      CACHED_PATHS: |
        bcheck
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set gcc-14 default
       # default is 13.2, unfortunately. This makes 14.x work
      run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 14 && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14
    - name: gcc version check
      run: gcc --version
    - name: install packages
      run: sudo apt-get install -y cmake
    - name: build
      run: ./scripts/build.sh
    - name: test
      run: cd build && ctest
